### ISSUE TITLE
Assign a default accept header if not set

### ISSUE THREAD

**Issue by scothis** [projectriff/streaming-http-adapter#4]
The streaming protocol requires a content-type for output streams, but not all http requests will send an accept header. If the request does not specify an accept header, use `*/*` as the default.

**Comment by ericbottard** [comment]
The adapter [already](https://github.com/projectriff/streaming-http-adapter/blob/aa65d99587ddd6117833b94d7c5c3538df57d03b/pkg/proxy/proxy.go#L84-L86) sets `application/octet-stream` as the default accept, which may be questionable.

**Comment by jldec** [comment]
Still seeing this when omitting Accept header for java uppercase function on riff (running latest snapshot):

cli
```
$ curl localhost -H "Host: ${host}.default.example.com" -H 'Content-Type: text/plain'  -w '\n' -d riff
rpc error: code = Unknown desc = 
```

deployer log
```
17:00:30.782 [grpc-default-executor-0] INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry - BeanDefinition for function name(s) '[upper]' can not be located. FunctionType will be based on class functions.Upper
java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:177)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:155)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstInner.onNext(FluxSwitchOnFirst.java:184)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drainRegular(AbstractStreamObserverAndPublisher.java:191)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drain(AbstractStreamObserverAndPublisher.java:271)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.onNext(AbstractStreamObserverAndPublisher.java:315)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:773)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ericbottard** [comment]
Please see above comment.

The bad experience you're likely referring to most certainly lies on the side of the java-function-invokers, and more precisely on the default MessageConverters that don't really play nice with `Accept=*/*`.

See https://github.com/projectriff/java-function-invoker/issues/142

**Comment by ericbottard** [comment]
I will close this issue and open a new one to change from application/octet-stream to */*.
